# Use postgres/example user/password credentials
version: '3.8'

volumes:
  database-data:

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_DB=${POSTGRES_DATABASE:-calcom}
      - DATABASE_URL=postgres://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@postgres:5432/${POSTGRES_DATABASE:-calcom}

  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_WEBAPP_URL: ${SERVICE_FQDN_CALCOM}
        NEXT_PUBLIC_LICENSE_CONSENT: ${NEXT_PUBLIC_LICENSE_CONSENT}
        CALCOM_TELEMETRY_DISABLED: ${CALCOM_TELEMETRY_DISABLED}
        NEXTAUTH_SECRET: $SERVICE_BASE64_32_SECRET
        CALENDSO_ENCRYPTION_KEY: $SERVICE_BASE64_32_SECRET
        DATABASE_URL: postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DATABASE:-calcom}
        DATABASE_DIRECT_URL: postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DATABASE:-calcom}

    restart: always
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - SERVICE_FQDN_CALCOM_3000
      - SERVICE_FQDN_CALCOM
      - EMAIL_SERVER_HOST=${SMTP_HOST:-test.example.com}
      - EMAIL_SERVER_PORT=${SMTP_PORT:-587}
      - EMAIL_SERVER_USER=${SMTP_USER:-test}
      - EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD:-test}
      - EMAIL_FROM=${MAIL_FROM:-test@example.com}
    depends_on:
      - database
